tap "homebrew/autoupdate", "https://github.com/kphrx/homebrew-autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "keys-pub/tap"
tap "kphrx/extract"
tap "kphrx/personal"
tap "messense/macos-cross-toolchains"
tap "reviewdog/tap"
brew "actionlint"
brew "gettext"
brew "gdbm"
brew "libxcb"
brew "xz"
brew "icu4c"
brew "mozjpeg", link: true
brew "openjdk"
brew "ant"
brew "webp"
brew "libtool"
brew "aria2"
brew "bat"
brew "chezmoi"
brew "cmake"
brew "rtmpdump"
brew "curl"
brew "elixir"
brew "jpeg", link: true
brew "ffmpeg"
brew "fnm"
brew "fontforge"
brew "fzf"
brew "ghq"
brew "git"
brew "git-flow"
brew "git-gui"
brew "git-lfs"
brew "git-svn"
brew "guile"
brew "libusb"
brew "gnupg"
brew "go"
brew "gopls"
brew "gpg-tui"
brew "gradle"
brew "gstreamer"
brew "helix"
brew "htop"
brew "imagemagick"
brew "iproute2mac"
brew "jq"
brew "kind"
brew "libyaml"
brew "llvm"
brew "lua"
brew "mas"
brew "mercurial"
brew "mitmproxy"
brew "neofetch"
brew "newsboat"
brew "p7zip"
brew "perl"
brew "pinentry-mac"
brew "powerline-go"
brew "rpm2cpio"
brew "rubberband"
brew "ruby"
brew "rustup-init"
brew "scrcpy"
brew "shellcheck"
brew "swiftlint"
brew "tig"
brew "unzip"
brew "vim"
brew "vint"
brew "w3m"
brew "wget"
brew "zinit"
brew "zlib"
brew "zola"
brew "zsh"
brew "zsh-completions"
brew "messense/macos-cross-toolchains/aarch64-unknown-linux-gnu"
brew "messense/macos-cross-toolchains/x86_64-unknown-linux-gnu"
brew "reviewdog/tap/reviewdog"
cask "airmail-beta"
cask "amazon-music"
cask "android-commandlinetools"
cask "android-file-transfer"
cask "android-studio"
cask "appcleaner"
cask "bitcoin-core"
cask "blackhole-16ch"
cask "blackhole-2ch"
cask "blackhole-64ch"
cask "brave-browser"
cask "curseforge"
cask "discord"
cask "docker"
cask "dropbox"
cask "epic-games"
cask "firefox-beta"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-cica-without-emoji"
cask "font-line-seed-jp"
cask "forklift"
cask "gog-galaxy"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "google-drive"
cask "inkscape"
cask "jpki"
cask "keybase"
cask "keys"
cask "kindle"
cask "kindle-comic-creator"
cask "kindle-previewer"
cask "lapce"
cask "libreoffice"
cask "lyrics-master"
cask "megasync"
cask "melonbooksviewer"
cask "minecraft"
cask "moradownloader"
cask "mousecape"
cask "nowplayingtweet"
cask "obs"
cask "onedrive"
cask "origin"
cask "parallels14"
cask "slack"
cask "steam"
cask "thedesk"
cask "vagrant"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
cask "waterfox"
cask "waterfox-classic"
cask "whalebird"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
mas "AppGraphics", id: 1097399493
mas "Developer", id: 640199958
mas "Disk Space Tab", id: 894146655
mas "Gapplin", id: 768053424
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "Image2icon", id: 992115977
mas "iMovie", id: 408981434
mas "Key Codes", id: 414568915
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
