[url "https://github.com/"]
	InsteadOf = github.com:
	InsteadOf = github:
	InsteadOf = git@github.com:
	InsteadOf = ssh://github.com/
[url "https://gist.github.com/"]
	InsteadOf = gist.github.com:
	InsteadOf = gist:
	InsteadOf = git@gist.github.com:
	InsteadOf = ssh://gist.github.com/
[url "https://gitlab.com/"]
	InsteadOf = gitlab.com:
	InsteadOf = gitlab:
	InsteadOf = git@gitlab.com:
	InsteadOf = ssh://gitlab.com/
[url "https://codeberg.org/"]
	InsteadOf = codeberg.org:
	InsteadOf = git@codeberg.org:
	InsteadOf = ssh://codeberg.org/
