[url "github.com:"]
	InsteadOf = github.com:
	InsteadOf = github:
	InsteadOf = git@github.com:
	InsteadOf = ssh://github.com/
	InsteadOf = https://github.com/
[url "gist.github.com:"]
	InsteadOf = gist.github.com:
	InsteadOf = gist:
	InsteadOf = git@gist.github.com:
	InsteadOf = ssh://gist.github.com/
	InsteadOf = https://gist.github.com/
[url "gitlab.com:"]
	InsteadOf = gitlab.com:
	InsteadOf = gitlab:
	InsteadOf = git@gitlab.com:
	InsteadOf = ssh://gitlab.com/
	InsteadOf = https://gitlab.com/
[url "https://codeberg.org/"]
	InsteadOf = codeberg.org:
	InsteadOf = git@codeberg.org:
	InsteadOf = ssh://codeberg.org/
